import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { LanguageProvider } from "../context/LanguageContext";
import StoreProvider from "../store/StoreProvider";
import Sidebar from "../components/sidebar/Sidebar";
import TopMenu from "@/components/top-menu/TopMenu";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      data-scroll-behavior="smooth"
      className={`${geistSans.variable} ${geistMono.variable}`}
    >
      <body className={geistSans.className}>
        <StoreProvider>
          <LanguageProvider>
            <div className="d-flex bg-light min-vh-100">
              {/* Сайдбар Слева*/}
              <Sidebar />
              {/* Top Menu */}
              <div className="w-100 d-flex flex-column main-content-layout">
                <TopMenu />
                {/* Main */}
                <main className="p-4 flex-grow-1" style={{ marginTop: "80px" }}>
                  {children}
                </main>
              </div>
            </div>
          </LanguageProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
