version: "3.8"

services:
  orders_postgres:
    image: postgres:15-alpine
    container_name: orders_postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret_password_2026
      POSTGRES_DB: orders_db
    ports:
      #  внешний_порт:внутренний_порт
      - "5433:5432"
    volumes:
      - orders_pg_data:/var/lib/postgresql/data

volumes:
  orders_pg_data:
